In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

In [4]:
train.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [8]:
test.head()

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0       0       0       0       0       0       0       0       0       0   
1       0       0       0       0       0       0       0       0       0   
2       0       0       0       0       0       0       0       0       0   
3       0       0       0       0       0       0       0       0       0   
4       0       0       0       0       0       0       0       0       0   

   pixel9  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 784 columns]

In [6]:
X_train = train.drop('label', axis= 1)
y_train = train['label']

In [7]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=100)
rfc.fit(X_train, y_train)

RandomForestClassifier()

In [9]:
y_pred = rfc.predict(test)

In [18]:
submission = pd.DataFrame()
submission['ImageId'] = range(1, len(y_pred)+1)
submission['Label'] = y_pred
submission.to_csv("submission.csv", index=False)

### Part 2: Accuracy and Confusion Matrix on Training Dataset

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
X = train.drop('label', axis= 1)
y = train['label']
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.3)

In [23]:
rfc = RandomForestClassifier(n_estimators=100)
rfc.fit(X_train, y_train)

RandomForestClassifier()

In [25]:
val_pred = rfc.predict(X_val)

In [28]:
from sklearn.metrics import confusion_matrix, accuracy_score
print(confusion_matrix(y_val,val_pred))
print(accuracy_score(y_val,val_pred))

[[1245    0    1    1    1    3    6    0    5    0]
 [   0 1391   10    3    5    1    1    2    3    0]
 [   8    3 1195    6    8    0    3    9   10    1]
 [   4    0   15 1247    0   22    2    8   14    5]
 [   2    3    3    0 1146    1    7    0    4   24]
 [   6    3    1   19    3 1061   10    3    7    5]
 [  14    1    2    0    1    9 1172    0    0    0]
 [   1    6   10    3    7    0    0 1314    3   16]
 [   1    6    5    8    4    5    5    0 1119   12]
 [   8    2    5   21   23    4    0   15    9 1243]]
0.962936507936508
